include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
  errors:
    record_literal_one_positional_no_trailing_comma: ignore
    leading_newlines_in_multiline_strings: ignore
    require_trailing_commas: ignore
  exclude:
    - test/**
    - test_driver/**
    - integration_test/**

linter:
  rules:
    public_member_api_docs: false
