name: tracking_practice
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_background_service: ^5.1.0
  flutter_localizations:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^13.0.3
  get_it: ^7.6.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  mocktail: ^1.0.4
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
