name: Automatic Trigger Deployment

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.title, 'Release')
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Extract and Generate Git Tag
        id: generate_tag
        run: |
          chmod +x ./scripts/generate_tag.sh
          ./scripts/generate_tag.sh "${{ github.event.pull_request.title }}"
      
      - name: Push Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # Build for Android
      - name: Build Android APK
        run: flutter build apk

      # Create artifacts directory and copy APK
      - name: Prepare Android artifact
        run: |
          mkdir -p artifacts
          cp build/app/outputs/flutter-apk/app-release.apk artifacts/app-${{ env.NEW_TAG }}.apk

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ env.NEW_TAG }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: "docs: :robot: CHANGELOG.md for ${{ github.ref_name }} [skip ci]"
          file_pattern: CHANGELOG.md

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/app-${{ env.NEW_TAG }}.apk"
          tag: ${{ env.NEW_TAG }}
          body: ${{ github.event.pull_request.body }}                  
          token: ${{ secrets.GITHUB_TOKEN }}              